//
// Created by cgtybsr on 07.06.18.
//

#ifndef OPC_UA_TESTING_PLATFORM_DISCOVERY_TEST_CLIENT_CLASS_H
#define OPC_UA_TESTING_PLATFORM_DISCOVERY_TEST_CLIENT_CLASS_H

#endif //OPC_UA_TESTING_PLATFORM_DISCOVERY_TEST_CLIENT_CLASS_H
